postgres:
  host: db.nnvuhwnbrodbyuddwytm.supabase.co
  port: 5432
  database: postgres
  user: postgres
  password: Maxmustard81845

neo4j:
  uri: neo4j+s://bc64524a.databases.neo4j.io
  user: bc64524a
  password: QxlECbAJVrXZw1bU5nDdoL870lP8DaKORiNsje2j9Nk

redis:

  host: https://topical-wolf-121660.upstash.io
  uri: rediss://default_ro:ggAAAAAAAds8AAIgcDHwBqeiUWadxHhpGNOwRXo-mZNGskHtE7onfHQAxX12UA@topical-wolf-121660.upstash.io:6379
  port: 6379
  db: reddBro
  api: af001889-7464-49d1-a0a7-a8fd8baa946b



