postgres:
  host: db.nnvuhwnbrodbyuddwytm.supabase.co
  port: 5432
  database: postgres
  user: postgres
  password: Maxmustard81845

neo4j:
  uri: bolt://localhost:7687
  user: neo4j
  password: password

redis:

  host: localhost
  port: 6379
  db: 0



