from pydantic import BaseModel,Field,ConfigDict
from typing import Optional
from uuid import UUID
from datetime import datetime


class customer(BaseModel):
    customer_id:UUID=Field(description="CustomerID")
    external_id:str=Field(description="ExternalID",min_length=2,max_length=30)
    is_fraud:bool=Field(description="IsFraud",default=False)
    created_at:datetime=Field(description="CreatedAt",default_factory=datetime.now)

class merchant(BaseModel):
    merchant_id:UUID=Field(description="MerchantID")
    external_id:str=Field(description="ExternalID",min_length=2,max_length=30)
    created_at:datetime=Field(description="CreatedAt",default_factory=datetime.now)

class card(BaseModel):
    card_id:UUID=Field(description="CardID")
    card_fingerprint:str=Field(description="CardFingerprint",min_length=2,max_length=50)
    card_network:str=Field(description="CardNetwork",min_length=2,max_length=25)
    card_category:str=Field(description="CardCategory",min_length=2,max_length=25)
    created_at:datetime=Field(description="CreatedAt",default_factory=datetime.now)

class device(BaseModel):
    device_id:UUID=Field(description="DeviceID")
    device_info:str=Field(description="DeviceInfo",min_length=2,max_length=300)
    device_type:str=Field(description="DeviceType",min_length=2,max_length=20)
    os:str=Field(description="OS",min_length=2,max_length=200)
    browser:str=Field(description="Browser",min_length=2,max_length=200)
    screen_res:str=Field(description="ScreenRes",min_length=2,max_length=30)
    created_at:datetime=Field(description="CreatedAt",default_factory=datetime.now)

class ips(BaseModel):
    ip_id:UUID=Field(description="IPID")
    ip_address:str=Field(description="IPAddress",min_length=2,max_length=45)
    country:str=Field(description="Country",min_length=2,max_length=10)
    vpn_flag:bool=Field(description="VPNFlag",default=False)
    tor_flag:bool=Field(description="TORFlag",default=False)

class transaction(BaseModel):
    tx_id:UUID=Field(description="TransactionID")
    customer_id:UUID=Field(description="CustomerID")
    merchant_id:UUID=Field(description="MerchantID")
    card_id:UUID=Field(description="CardID")
    device_id:UUID=Field(description="DeviceID")
    ip_id:UUID=Field(description="IPID")
    amount:float=Field(description="Amount")
    tx_type:str=Field(description="TransactionType",min_length=2,max_length=20)
    product_code:str=Field(description="ProductCode",min_length=2,max_length=20)
    balance_before:float=Field(description="BalanceBefore")
    balance_after:float=Field(description="BalanceAfter")
    is_fraud:bool=Field(description="IsFraud",default=False)
    is_flagged:bool=Field(description="IsFlagged",default=False)
    timestamp:datetime=Field(description="Timestamp")
    created_at:datetime=Field(description="CreatedAt",default_factory=datetime.now)

class transaction_features(BaseModel):
    feature_id:UUID=Field(description="FeatureID")
    transaction_id:UUID=Field(description="TransactionID")

    
    c1: float=Field(description="C1")
    c2: float=Field(description="C2")
    c3: float=Field(description="C3")
    c4: float=Field(description="C4")
    c5: float=Field(description="C5")
    c6: float=Field(description="C6")
    c7: float=Field(description="C7")
    c8: float=Field(description="C8")
    c9: float=Field(description="C9")
    c10: float=Field(description="C10")
    c11: float=Field(description="C11")
    c12: float=Field(description="C12")
    c13: float=Field(description="C13")
    c14: float=Field(description="C14")

    d1: float=Field(description="D1")
    d2: float=Field(description="D2")
    d3: float=Field(description="D3")
    d4: float=Field(description="D4")
    d5: float=Field(description="D5")
    d6: float=Field(description="D6")
    d7: float=Field(description="D7")
    d8: float=Field(description="D8")
    d9: float=Field(description="D9")
    d10: float=Field(description="D10")
    d11: float=Field(description="D11")
    d12: float=Field(description="D12")
    d13: float=Field(description="D13")
    d14: float=Field(description="D14")
    d15: float=Field(description="D15")

    m1: str=Field(description="M1")
    m2: str=Field(description="M2")
    m3: str=Field(description="M3")
    m4: str=Field(description="M4")
    m5: str=Field(description="M5")
    m6: str=Field(description="M6")
    m7: str=Field(description="M7")
    m8: str=Field(description="M8")
    m9: str=Field(description="M9")
    created_at:datetime=Field(description="CreatedAt",default_factory=datetime.now)

class customer_identity(BaseModel):
    identity_id: UUID = Field(description="Unique identifier for the identity record")
    transaction_id: UUID = Field(description="ID of the associated transaction")
    customer_id: UUID = Field(description="ID of the associated customer")
    id_01: float = Field(description="Identity feature 01")
    id_02: float = Field(description="Identity feature 02")
    id_03: float = Field(description="Identity feature 03")
    id_04: float = Field(description="Identity feature 04")
    id_05: float = Field(description="Identity feature 05")
    id_06: float = Field(description="Identity feature 06")
    id_07: float = Field(description="Identity feature 07")
    id_08: float = Field(description="Identity feature 08")
    id_09: float = Field(description="Identity feature 09")
    id_10: float = Field(description="Identity feature 10")
    id_11: float = Field(description="Identity feature 11")
    id_12: str = Field(max_length=10,description="Identity categorical feature 12")
    id_13: float = Field(description="Identity feature 13")
    id_14: float = Field(description="Identity feature 14")
    id_15: str = Field(max_length=20,description="Identity categorical feature 15")
    id_16: str = Field(max_length=20,description="Identity categorical feature 16")
    id_17: float = Field(description="Identity feature 17")
    id_18: float = Field(description="Identity feature 18")
    id_19: float = Field(description="Identity feature 19")
    id_20: float = Field(description="Identity feature 20")
    id_21: float = Field(description="Identity feature 21")
    id_22: float = Field(description="Identity feature 22")
    id_23: str = Field(max_length=20,description="Identity categorical feature 23")
    id_24: float = Field(description="Identity feature 24")
    id_25: float = Field(description="Identity feature 25")
    id_26: float = Field(description="Identity feature 26")
    id_27: float = Field(description="Identity feature 27")
    id_28: str = Field(max_length=20,description="Identity categorical feature 28")
    id_29: str = Field(max_length=20,description="Identity categorical feature 29")
    id_30: str = Field(max_length=100, description="Identity categorical feature 30")
    id_31: str = Field(max_length=100, description="Identity categorical feature 31")
    id_32: float = Field(description="Identity feature 32")
    id_33: str = Field(max_length=30, description="Identity categorical feature 33")
    id_34: str = Field(max_length=20, description="Identity categorical feature 34")
    id_35: str = Field(max_length=20, description="Identity categorical feature 35")
    id_36: str = Field(max_length=20, description="Identity categorical feature 36")
    id_37: str = Field(max_length=20, description="Identity categorical feature 37")
    id_38: str = Field(max_length=20, description="Identity categorical feature 38")
    created_at: datetime = Field(description="Timestamp when the identity record was created")

class login_event(BaseModel):
    event_id:UUID=Field(description="EventID")
    customer_id:UUID=Field(description="CustomerID")
    ip_id:UUID=Field(description="IPID")
    timestamp:datetime=Field(description="Timestamp")
    created_at:datetime=Field(description="CreatedAt",default_factory=datetime.now)

class prediction(BaseModel):
    prediction_id:UUID=Field(description="PredictionID")
    customer_id:UUID=Field(description="CustomerID")
    fraud_score:float=Field(description="FraudScore")
    top_feature:str=Field(description="TopFeature",min_length=2,max_length=100)
    scored_at:datetime=Field(description="ScoredAt",default_factory=datetime.now)

